### ISSUE TITLE
NOT gate

### ISSUE THREAD

**Issue by schronck** [agoraxyz/requiem#11]
# Description

A NOT gate could be helpful in case it is necessary that a certain requirement is not met.

**Comment by PopcornPaws** [comment]
I was thinking about adding a NOT gate as well, but then I thought you can just define the requirement as `balance <= target` instead of `NOT(balance > target)`. If you need `NOT(AND(x, y))`, then just use `NAND`, etc. Anything more convoluted like `NOT(a AND (b OR c) OR d)` is not very likely in my opinion. I can only think of `NOT(allowlist.is_member(user))`, being a possible usecase, but is it really something that would make sense?

Of course I might miss some valid usecases but for now I don't really see the point of adding a NOT gate to this logic. What do you think @schronck? I'm not against it, it's just that it might be a bit tricky to incorporate into the parsing logic.

**Comment by schronck** [comment]
Yeah, you are right. After thinking about it I came to the same conclusion. Anyways, if someone really wants to use a `NOT` gate for "requirement A", they can still use `A NAND A` and achieve the same result.
